package rules

import com.zl.study.drools.model.SearchRule;
import com.zl.study.drools.enums.SearchEnum
import java.util.ArrayList
import java.util.List;
/*规则名字*/
rule "law"
	when
	/*规则条件，里面出来的结果只能是ture或者false*/
		productObject: SearchRule(searchValue matches ".*关于.+的公告\\(通知\\)"
		|| searchValue matches ".*法" || searchValue matches ".*暂行条例"
		|| searchValue matches ".*实施细则")
	then
		productObject.setDocType(3);
	end
rule "law_writ_no"
	when
	/*对productObject进行参数绑定，当条件满足时*/
		productObject: SearchRule(searchValue matches ".[〔〕].*" || searchValue matches ".*\\d "
		|| searchValue matches ".*\\d号" || searchValue matches ".*[号令函].*")
	then
	/*对productObject进行操作*/
	    List<SearchEnum> list = new ArrayList<>();
	    list.add(SearchEnum.WRIT_NO);
	    productObject.setSearchEnumList(list);
		productObject.setDocType(3);
	end
